### ISSUE TITLE
Themes assets not found on production

### ISSUE THREAD

**Issue by fedemoretti** [owen2345/camaleon-cms#348]
Hello, I deployed an application to a production server and did assets precompilation using `bundle exec rake assets:precompile`. 
However, some assets inside my custom theme are not served (fonts, images, etc).

Do I need to include them in `initializers/assets.rb` ?

**Comment by owen2345** [comment]
Hi @fedemoretti 
which server are you using?
because Camaleon come already configured to precompile all assets.
And is there any error precompiling?

**Comment by fedemoretti** [comment]
Hi @owen2345, thanks for your quick response. I did some research and I found the problem was we were using more than one SCSS file and only application.css.scss gets precompiled.
We changed it to require the other files inside application.css.scss and everything is working now.
Thanks! I'm closing the issue.

**Comment by fedemoretti** [comment]
Hi @owen2345, I thought the problem was solved but it was not. The problem is SASS assets helper methods are not working inside my scss files. I have a font-face setup as:
```sass
@font-face {
  font-family: 'Lato';

  src: asset-theme-url('fonts/Lato-Bold.eot'); /* IE9 Compat Modes */
  src: asset-theme-url('fonts/Lato-Bold.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
    asset-theme-url('fonts/Lato-Bold.woff2') format('woff2'), /* Modern Browsers */
    asset-theme-url('fonts/Lato-Bold.woff') format('woff'), /* Modern Browsers */
    asset-theme-url('fonts/Lato-Bold.ttf') format('truetype');
  font-style: normal;
  font-weight: 700;
  text-rendering: optimizeLegibility;
}
```

And my compiled CSS results in:
```css
/* Webfont: Lato-Bold */
@font-face {
  font-family: 'Lato';
  src: asset-theme-url("fonts/Lato-Bold.eot");
  /* IE9 Compat Modes */
  src: asset-theme-url("fonts/Lato-Bold.eot?#iefix") format("embedded-opentype"), asset-theme-url("fonts/Lato-Bold.woff2") format("woff2"), asset-theme-url("fonts/Lato-Bold.woff") format("woff"), asset-theme-url("fonts/Lato-Bold.ttf") format("truetype");
  font-style: normal;
  font-weight: 700;
  text-rendering: optimizeLegibility;
}
```

My fonts are in `apps/themes/my_theme/assets/fonts`
I have tried other helper methods like: `asset_theme_path` and `asset_theme_url` but none of them seem to work.

Any ideas?
